rules:
  "@mr-linter/has_any_labels":
    labels:
      - Feature
      - Bug
      - Docs
      - Tests
      - Optimization

  "@mr-linter/description_template":
    - definition: description must have list of features
      template: |
        ## Added
        {text_multiline}
      when:
        labels:
          has: "Feature"

    - definition: description must have list of fixed bugs
      template: |
        ## Fixed
        {text_multiline}
      when:
        labels:
          has: "Bug"

  "@mr-linter/title_must_starts_with_any_prefix":
    prefixes:
      - '[Feature]'
      - '[Bug]'
      - '[Docs]'
      - '[Tests]'
      - '[Optimization]'

  "@mr-linter/description_not_empty": {}

  "@mr-linter/changelog_has_new_release":
    when:
      targetBranch:
        equals: "master"
      title:
        notStartsAny:
          - '[Tests]'
          - '[Docs]'

  "@mr-linter/no_ssh_keys":
    stopOnFirstFailure: true
    critical: false

  "@mr-linter/has_changes":
    - changes:
      - file: "src/Version.php"
        updatedPhpConstant: "VERSION"
      when:
        targetBranch:
          equals: "master"
        title:
          notStartsAny:
            - '[Tests]'
            - '[Docs]'

  "@mr-linter/disable_file_extensions":
    extensions:
      - pem
      - pub

  custom:
    - definition: "Branch must be in kebab-case"
      rules:
        sourceBranch:
          isKebabCase: true

    - definition: "Split feature / bug PR"
      rules:
        labels:
          notIntersect:
            - Feature
            - Bug

notifications:
  channels:
    dev:
      type: 'telegram_bot'
      chat_id: 'env(MR_LINTER_TELEGRAM_CHAT_ID)'
      bot_token: 'env(MR_LINTER_TELEGRAM_BOT_TOKEN)'
      sound_at: '09:00-21:00'
  on:
    lint_finished:
      channel: 'dev'
      template: |
        👀 Review on PR "{{ request.title | raw }}" by {{ request.author.login }} at {{ request.createdAt.format('Y-m-d H:i') }}
        
        🌲 {{ request.sourceBranch }} ➡ {{ request.targetBranch }}
        
        🌐 {{ request.uri }}
        
        📉 Notes: {{ result.notes.count }}
        
        {% for note in result.notes %}
        - {{ note.description | raw }}
        {% endfor %}

ci:
  github_actions:
    credentials:
      token: 'env(MR_LINTER_GITHUB_HTTP_TOKEN)'

metrics:
  storage:
    prometheusPushGateway:
      address: http://host.docker.internal:9091

comments:
  strategy: 'single'
  messages:
    - template: |
        I found {{ result.notes.count }} notes in your Pull Request:
        {% for note in result.notes %}
        - {{ note.description | raw }}
        {% endfor %}
      when:
        result.notes:
          isEmpty: false

    - template: |
        I didn't find any notes in your Pull Request.
      when:
        result.notes:
          isEmpty: true
