rules:
  "@mr-linter/has_any_labels_of":
    labels:
      - Feature
      - Bug
      - Docs
      - Tests
      - Optimization

  "@mr-linter/title_must_starts_with_any_prefix":
    prefixes:
      - '[Feature]'
      - '[Bug]'
      - '[Docs]'
      - '[Tests]'
      - '[Optimization]'

  "@mr-linter/description_not_empty": {}

  "@mr-linter/has_changes":
    changes:
      - file: "src/Console/Application/Application.php"
        updatedPhpConstant: "VERSION"
    when:
      targetBranch:
        equals: "master"

credentials:
  github_actions: "env(MR_LINTER_GITHUB_HTTP_TOKEN)"
